# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gavinswilson/code/Sudoku/sudokusolver/ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sudoku(object):
    def setupUi(self, Sudoku):
        Sudoku.setObjectName("Sudoku")
        Sudoku.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Sudoku)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(60, 40, 141, 141))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.three = QtWidgets.QPushButton(self.frame)
        self.three.setGeometry(QtCore.QRect(100, 20, 21, 20))
        self.three.setObjectName("three")
        self.One = QtWidgets.QPushButton(self.frame)
        self.One.setGeometry(QtCore.QRect(20, 20, 20, 21))
        self.One.setObjectName("One")
        self.Two = QtWidgets.QPushButton(self.frame)
        self.Two.setGeometry(QtCore.QRect(60, 20, 21, 20))
        self.Two.setObjectName("Two")
        self.four = QtWidgets.QPushButton(self.frame)
        self.four.setGeometry(QtCore.QRect(20, 60, 21, 20))
        self.four.setObjectName("four")
        self.five = QtWidgets.QPushButton(self.frame)
        self.five.setGeometry(QtCore.QRect(60, 60, 21, 20))
        self.five.setObjectName("five")
        self.six = QtWidgets.QPushButton(self.frame)
        self.six.setGeometry(QtCore.QRect(100, 60, 21, 20))
        self.six.setObjectName("six")
        self.seven = QtWidgets.QPushButton(self.frame)
        self.seven.setGeometry(QtCore.QRect(20, 100, 21, 20))
        self.seven.setObjectName("seven")
        self.eight = QtWidgets.QPushButton(self.frame)
        self.eight.setGeometry(QtCore.QRect(60, 100, 21, 20))
        self.eight.setObjectName("eight")
        self.nine = QtWidgets.QPushButton(self.frame)
        self.nine.setGeometry(QtCore.QRect(100, 100, 21, 20))
        self.nine.setObjectName("nine")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(220, 20, 561, 541))
        self.tableView.setObjectName("tableView")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(60, 480, 89, 25))
        self.pushButton.setObjectName("pushButton")
        Sudoku.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Sudoku)
        self.statusbar.setObjectName("statusbar")
        Sudoku.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(Sudoku)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuSolver = QtWidgets.QMenu(self.menuBar)
        self.menuSolver.setObjectName("menuSolver")
        Sudoku.setMenuBar(self.menuBar)
        self.action_Open = QtWidgets.QAction(Sudoku)
        self.action_Open.setObjectName("action_Open")
        self.action_Close = QtWidgets.QAction(Sudoku)
        self.action_Close.setObjectName("action_Close")
        self.action_Solve = QtWidgets.QAction(Sudoku)
        self.action_Solve.setObjectName("action_Solve")
        self.menuFile.addAction(self.action_Open)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Close)
        self.menuSolver.addAction(self.action_Solve)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuSolver.menuAction())

        self.retranslateUi(Sudoku)
        self.action_Close.triggered.connect(Sudoku.close)
        QtCore.QMetaObject.connectSlotsByName(Sudoku)
        Sudoku.setTabOrder(self.One, self.Two)
        Sudoku.setTabOrder(self.Two, self.three)
        Sudoku.setTabOrder(self.three, self.four)
        Sudoku.setTabOrder(self.four, self.five)
        Sudoku.setTabOrder(self.five, self.six)
        Sudoku.setTabOrder(self.six, self.seven)
        Sudoku.setTabOrder(self.seven, self.eight)
        Sudoku.setTabOrder(self.eight, self.nine)
        Sudoku.setTabOrder(self.nine, self.tableView)
        Sudoku.setTabOrder(self.tableView, self.pushButton)

    def retranslateUi(self, Sudoku):
        _translate = QtCore.QCoreApplication.translate
        Sudoku.setWindowTitle(_translate("Sudoku", "MainWindow"))
        self.three.setText(_translate("Sudoku", "3"))
        self.One.setText(_translate("Sudoku", "1"))
        self.Two.setText(_translate("Sudoku", "2"))
        self.four.setText(_translate("Sudoku", "4"))
        self.five.setText(_translate("Sudoku", "5"))
        self.six.setText(_translate("Sudoku", "6"))
        self.seven.setText(_translate("Sudoku", "7"))
        self.eight.setText(_translate("Sudoku", "8"))
        self.nine.setText(_translate("Sudoku", "9"))
        self.pushButton.setText(_translate("Sudoku", "PushButton"))
        self.menuFile.setTitle(_translate("Sudoku", "File"))
        self.menuSolver.setTitle(_translate("Sudoku", "Solver"))
        self.action_Open.setText(_translate("Sudoku", "Open"))
        self.action_Open.setShortcut(_translate("Sudoku", "Ctrl+O"))
        self.action_Close.setText(_translate("Sudoku", "Close"))
        self.action_Close.setShortcut(_translate("Sudoku", "Ctrl+X"))
        self.action_Solve.setText(_translate("Sudoku", "Solve"))
        self.action_Solve.setShortcut(_translate("Sudoku", "Ctrl+D"))
